# Generated by Django 4.2.2 on 2023-06-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='precio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='id_categoria',
            field=models.ForeignKey(db_column='idCategoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.categoria'),
        ),
    ]
