# Generated by Django 4.2.2 on 2023-06-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_categoria_post_precio_post_id_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dateaprobado',
        ),
        migrations.AddField(
            model_name='post',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
