# Generated by Django 4.2.2 on 2023-06-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_dateaprobado_post_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
